create table actions (id varchar(255) not null, execute_after timestamp not null, type varchar(255) not null, status varchar(255) not null, actor_id varchar(255) not null, subject_id varchar(255) not null, parameters clob not null, failure clob, primary key (id));
create table aliases (id varchar(255) not null, target_id varchar(255) not null, primary key (id));
create table files (id varchar(255) not null, description varchar(1024) not null, size_in_bytes integer not null, data_id varchar(255) not null, mime_type_primary varchar(255) not null, mime_type_sub varchar(255) not null, primary key (id), unique (data_id));
create table folders (id varchar(255) not null, sort_order varchar(255) not null, primary key (id));
create table logentries (id varchar(255) not null, actor_id varchar(255) not null, action varchar(255) not null, happened_on timestamp not null, subject_type varchar(255) not null, subject_id varchar(255) not null, message varchar(1024) not null, detail clob not null, index_position bigint not null, recorded_on timestamp not null, major_change bit not null, primary key (id));
create table pages (id varchar(255) not null, working_copy clob, primary key (id));
create table paragraphs (page_id varchar(255) not null, name varchar(255) not null, type varchar(255) not null, value_text clob, value_boolean bit, value_date timestamp, primary key (page_id, name, type));
create table passwords (id varchar(255) not null, version bigint not null, hash binary(255) not null, user_id varchar(255) not null unique, primary key (id));
create table resource_metadata (resource_id varchar(255) not null, datum_value varchar(1000) not null, datum_key varchar(100) not null, primary key (resource_id, datum_key));
create table resource_roles (resource_id varchar(255) not null, role varchar(255) not null, primary key (resource_id, role));
create table resource_tags (resource_id varchar(255) not null, tag_value varchar(255) not null, tag_index integer not null, primary key (resource_id, tag_index));
create table resources (id varchar(255) not null, version bigint not null, title varchar(256) not null, in_main_menu bit not null, date_created timestamp not null, date_changed timestamp not null, template_id varchar(255), locked_by_id varchar(255), published_by_id varchar(255), name varchar(256) not null, parent_id varchar(255), parent_index integer, primary key (id));
create table searches (id varchar(255) not null, primary key (id));
create table settings (id varchar(255) not null, version bigint not null, value varchar(255) not null, name varchar(255) not null unique, primary key (id));
create table templates (id varchar(255) not null, title varchar(256) not null, description varchar(1024) not null, body clob not null, definition clob not null, primary key (id));
create table user_roles (user_id varchar(255) not null, role varchar(255) not null, primary key (user_id, role));
create table users (id varchar(255) not null, version bigint not null, username varchar(255) not null unique, email varchar(255) not null, primary key (id));
alter table actions add constraint FKBAC048FD432B573B foreign key (subject_id) references resources;
alter table actions add constraint FKBAC048FD584BF10F foreign key (actor_id) references users;
alter table aliases add constraint FKC97D4EFE655C6748 foreign key (id) references resources;
alter table aliases add constraint FKC97D4EFE34BFA4B6 foreign key (target_id) references resources;
alter table files add constraint FK5CEBA77655C6748 foreign key (id) references resources;
alter table folders add constraint FKD74671C5655C6748 foreign key (id) references resources;
alter table logentries add constraint FKC5636CCC584BF10F foreign key (actor_id) references users;
alter table pages add constraint FK657EFC4655C6748 foreign key (id) references resources;
alter table paragraphs add constraint FK11C964C58AC5B0F9 foreign key (page_id) references pages;
alter table passwords add constraint FKC8AD9938B1E85779 foreign key (user_id) references users;
alter table resource_metadata add constraint FK85E79840AEF1E519 foreign key (resource_id) references resources;
alter table resource_roles add constraint FK11F6F34CAEF1E519 foreign key (resource_id) references resources;
alter table resource_tags add constraint FK3A6381AAAEF1E519 foreign key (resource_id) references resources;
alter table resources add constraint FK89CCBE252A3B35DC foreign key (published_by_id) references users;
alter table resources add constraint FK89CCBE259465FD99 foreign key (template_id) references templates;
alter table resources add constraint FK89CCBE2526915F1D foreign key (parent_id) references folders;
alter table resources add constraint FK89CCBE25474981F8 foreign key (locked_by_id) references users;
alter table searches add constraint FK34F7A856655C6748 foreign key (id) references resources;
alter table templates add constraint FK761EC339655C6748 foreign key (id) references resources;
alter table user_roles add constraint FK73429949B1E85779 foreign key (user_id) references users;
CREATE TABLE data( id VARCHAR(255) NOT NULL, version INTEGER NOT NULL, bytes BLOB NOT NULL );
CREATE SEQUENCE log_entry_index START WITH 1 INCREMENT BY 1 CACHE 0;
ALTER TABLE logentries ALTER COLUMN index_position SET DEFAULT nextval('LOG_ENTRY_INDEX');
ALTER TABLE logentries ALTER COLUMN recorded_on SET DEFAULT CURRENT_TIMESTAMP();
INSERT INTO SETTINGS (id, version, value, name) VALUES ('145e827a-0f11-41bf-af0b-ad9a4a982c03', 0, '0', 'DATABASE_VERSION');
