create table actions (id varchar(255) not null, execute_after datetime not null, type varchar(255) not null, status varchar(255) not null, actor_id varchar(255) not null, subject_id varchar(255) not null, parameters text not null, failure text null, primary key (id));
create table aliases (id varchar(255) not null, target_id varchar(255) not null, primary key (id));
create table files (id varchar(255) not null, description varchar(1024) not null, size_in_bytes int not null, data_id varchar(255) not null, mime_type_primary varchar(255) not null, mime_type_sub varchar(255) not null, primary key (id), unique (data_id));
create table folders (id varchar(255) not null, sort_order varchar(255) not null, primary key (id));
create table logentries (id varchar(255) not null, actor_id varchar(255) not null, action varchar(255) not null, happened_on datetime not null, subject_type varchar(255) not null, subject_id varchar(255) not null, message varchar(1024) not null, detail text not null, index_position numeric(19,0) not null, recorded_on datetime not null, major_change tinyint not null, primary key (id));
create table pages (id varchar(255) not null, working_copy text null, primary key (id));
create table paragraphs (page_id varchar(255) not null, name varchar(255) not null, type varchar(255) not null, value_text text null, value_boolean tinyint null, value_date datetime null, primary key (page_id, name, type));
create table passwords (id varchar(255) not null, version numeric(19,0) not null, hash varbinary(255) not null, user_id varchar(255) not null unique, primary key (id));
create table resource_metadata (resource_id varchar(255) not null, datum_value varchar(1000) not null, datum_key varchar(100) not null, primary key (resource_id, datum_key));
create table resource_roles (resource_id varchar(255) not null, role varchar(255) not null, primary key (resource_id, role));
create table resource_tags (resource_id varchar(255) not null, tag_value varchar(255) not null, tag_index int not null, primary key (resource_id, tag_index));
create table resources (id varchar(255) not null, version numeric(19,0) not null, title varchar(256) not null, in_main_menu tinyint not null, date_created datetime not null, date_changed datetime not null, template_id varchar(255) null, locked_by_id varchar(255) null, published_by_id varchar(255) null, name varchar(256) not null, parent_id varchar(255) null, parent_index int null, primary key (id));
create table searches (id varchar(255) not null, primary key (id));
create table settings (id varchar(255) not null, version numeric(19,0) not null, value varchar(255) not null, name varchar(255) not null unique, primary key (id));
create table templates (id varchar(255) not null, title varchar(256) not null, description varchar(1024) not null, body text not null, definition text not null, primary key (id));
create table user_roles (user_id varchar(255) not null, role varchar(255) not null, primary key (user_id, role));
create table users (id varchar(255) not null, version numeric(19,0) not null, username varchar(255) not null unique, email varchar(255) not null, primary key (id));
alter table actions add constraint FKBAC048FD432B573B foreign key (subject_id) references resources;
alter table actions add constraint FKBAC048FD584BF10F foreign key (actor_id) references users;
alter table aliases add constraint FKC97D4EFE655C6748 foreign key (id) references resources;
alter table aliases add constraint FKC97D4EFE34BFA4B6 foreign key (target_id) references resources;
alter table files add constraint FK5CEBA77655C6748 foreign key (id) references resources;
alter table folders add constraint FKD74671C5655C6748 foreign key (id) references resources;
alter table logentries add constraint FKC5636CCC584BF10F foreign key (actor_id) references users;
alter table pages add constraint FK657EFC4655C6748 foreign key (id) references resources;
alter table paragraphs add constraint FK11C964C58AC5B0F9 foreign key (page_id) references pages;
alter table passwords add constraint FKC8AD9938B1E85779 foreign key (user_id) references users;
alter table resource_metadata add constraint FK85E79840AEF1E519 foreign key (resource_id) references resources;
alter table resource_roles add constraint FK11F6F34CAEF1E519 foreign key (resource_id) references resources;
alter table resource_tags add constraint FK3A6381AAAEF1E519 foreign key (resource_id) references resources;
alter table resources add constraint FK89CCBE252A3B35DC foreign key (published_by_id) references users;
alter table resources add constraint FK89CCBE259465FD99 foreign key (template_id) references templates;
alter table resources add constraint FK89CCBE2526915F1D foreign key (parent_id) references folders;
alter table resources add constraint FK89CCBE25474981F8 foreign key (locked_by_id) references users;
alter table searches add constraint FK34F7A856655C6748 foreign key (id) references resources;
alter table templates add constraint FK761EC339655C6748 foreign key (id) references resources;
alter table user_roles add constraint FK73429949B1E85779 foreign key (user_id) references users;
CREATE TABLE data( id VARCHAR(255) NOT NULL, version INTEGER NOT NULL, bytes varbinary(max) NOT NULL );
BEGIN ALTER TABLE logentries DROP COLUMN index_position ALTER TABLE logentries ADD index_position numeric(19,0) IDENTITY(1,1) END;
BEGIN ALTER TABLE logentries DROP COLUMN recorded_on ALTER TABLE logentries ADD recorded_on DATETIME DEFAULT CURRENT_TIMESTAMP END;
INSERT INTO SETTINGS (id, version, value, name) VALUES ('145e827a-0f11-41bf-af0b-ad9a4a982c03', 0, '0', 'DATABASE_VERSION');
