DROP TRIGGER logentry_timestamp;
DROP TRIGGER logentry_autonumber;
DROP SEQUENCE log_entry_index;
drop table action_fail_params cascade constraints;
drop table action_params cascade constraints;
drop table actions cascade constraints;
drop table aliases cascade constraints;
drop table file_revision_properties cascade constraints;
drop table file_revisions cascade constraints;
drop table file_wc_properties cascade constraints;
drop table file_wcopies cascade constraints;
drop table files cascade constraints;
drop table folders cascade constraints;
drop table logentries cascade constraints;
drop table page_revision_paragraphs cascade constraints;
drop table page_revisions cascade constraints;
drop table page_wcopies cascade constraints;
drop table page_wcopy_paragraphs cascade constraints;
drop table pages cascade constraints;
drop table resource_metadata cascade constraints;
drop table resource_roles cascade constraints;
drop table resource_tags cascade constraints;
drop table resources cascade constraints;
drop table searches cascade constraints;
drop table settings cascade constraints;
drop table template_revisions cascade constraints;
drop table templates cascade constraints;
drop table user_metadata cascade constraints;
drop table user_roles cascade constraints;
drop table users cascade constraints;
